version: '3.8'

networks:
  gv_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

  prometheus:
    container_name: gestao_vagas_prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: E:\Code\gestao_vagas\.config\prometheus.yml
        target: /etc/prometheus/prometheus.yml
        read_only: true
      - prometheus_data:/prometheus
    networks:
      - gv_network

  grafana:
    container_name: gestao_vagas_grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - gv_network